// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmUaURjmp-QcMjUmArO_zA_wQqDoqTWHU',
    appId: '1:248755296662:web:a039eeea15bdfbff7465b7',
    messagingSenderId: '248755296662',
    projectId: 'reddit-clone-8e8c7',
    authDomain: 'reddit-clone-8e8c7.firebaseapp.com',
    storageBucket: 'reddit-clone-8e8c7.firebasestorage.app',
    measurementId: 'G-C6SDEHV9GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8anDbUZ4pT-nlBZMmye905ks1knTrF5w',
    appId: '1:248755296662:android:5ac82892deba57b07465b7',
    messagingSenderId: '248755296662',
    projectId: 'reddit-clone-8e8c7',
    storageBucket: 'reddit-clone-8e8c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjONRsZWk-zQvPwQjbMB5FCaCn8KCkPq4',
    appId: '1:248755296662:ios:588bef52c8ee9c377465b7',
    messagingSenderId: '248755296662',
    projectId: 'reddit-clone-8e8c7',
    storageBucket: 'reddit-clone-8e8c7.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );
}
